--- #YAML:1.0
name: FSA-Rules
version: 0.02
author:
  - David Wheeler <david@kineticode.com>
abstract: A simple Perl state machine
license: perl
build_requires:
  Test::Simple: 0.17
provides:
  FSA::Rules:
    file: lib/FSA/Rules.pm
    version: 0.02
generated_by: Module::Build version 0.26
