---
name: FSA-Rules
version: 0.28
author:
  - |-
    David Wheeler <david@kineticode.com>
    Curtis "Ovid" Poe <eop_divo_sitruc@yahoo.com> (reverse the name to email him)
abstract: Build simple rules-based state machines in Perl
license: perl
resources:
  license: http://dev.perl.org/licenses/
configure_requires:
  Module::Build: 0.2701
requires:
  perl: 5.6.2
build_requires:
  Module::Build: 0.2701
  Test::More: 0.17
recommends:
  B::Deparse: 0.61
  GraphViz: 2.00
  Storable: 2.05
  Test::Pod: 1.20
  Test::Spelling: 0
  Text::Wrap: 0
provides:
  FSA::Rules:
    file: lib/FSA/Rules.pm
    version: 0.28
  FSA::State:
    file: lib/FSA/Rules.pm
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
