--- #YAML:1.0
name: FSA-Machine
version: 0.07
author:
  - David Wheeler <david@kineticode.com>
abstract: Build simple state machines in Perl
license: perl
build_requires:
  Test::Simple: 0.17
provides:
  FSA::Machine:
    file: lib/FSA/Machine.pm
    version: 0.07
generated_by: Module::Build version 0.26
