---
name: FSA-Rules
version: 0.22
author: []
abstract: Build simple rules-based state machines in Perl
license: perl
requires:
  Clone: 0.15
recommends:
  GraphViz: 2.00
  Text::Wrap: 0
build_requires:
  Test::Simple: 0.17
provides:
  FSA::Rules:
    file: lib/FSA/Rules.pm
    version: 0.22
  FSA::State:
    file: lib/FSA/Rules.pm
generated_by: Module::Build version 0.2702
