--- #YAML:1.0
name: FSA-Rules
version: 0.20
author:
  - David Wheeler <david@kineticode.com>
abstract: Build simple rules-based state machines in Perl
license: perl
requires:
  Clone: 0.15
recommends:
  GraphViz: 2.00
build_requires:
  Test::Simple: 0.17
provides:
  FSA::Rules:
    file: lib/FSA/Rules.pm
    version: 0.20
  FSA::State:
    file: lib/FSA/Rules.pm
    version: 0.20
generated_by: Module::Build version 0.26
